#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com\ permanent;/" /etc/nginx/sites-available/default

sudo service nginx restart
