#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx

# custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/listen [::]:80 default_server;/\
listen [::]:80 default_server;\n\n\
\terror_page 404 \/404.html;\n\
\tlocation = \/404.html {\n\
\t\troot \/var\/www\/html;\n\
\t\tinternal;\n\
\t}/" /etc/nginx/sites-available/default

sudo service nginx restart
