#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
echo "add_header X-Served-By $(hostname);" | sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart
