#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

lb_algo="roundrobin"

ip1="54.146.90.145"
ip2="18.204.14.136"

frontend="frontend lb-01
        bind *:80
        mode http
        default_backend nginx_webservers"

backend="backend nginx_webservers
        balance $lb_algo
        server web-01 $ip1:80 check
        server web-02 $ip2:80 check"

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

if ! grep -q -e "$frontend" -e "$backend" /etc/haproxy/haproxy.cfg
then
        echo "Adding configuration. Please wait..."
        # Directly echo the configuration lines into the HAProxy configuration file
        echo -e "\n$frontend\n\n$backend" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
        echo "Aye Captain! Done!!!"
else
        echo "the configuration is already present! DRY"
fi

sudo service haproxy restart
