#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd
# using the while loop + IFS

file="/etc/passwd"
while IFS= read -r line
do
	username=$(echo "$line" | cut -d: -f5)
	pass=$(echo "$line" | cut -d: -f2)
	userID=$(echo "$line" | cut -d: -f3)
	dirPath=$(echo "$line" | cut -d: -f6)
	sh=$(echo "$line" | cut -d: -f7)
	idInfo=$(echo "$line" | cut -d: -f5)
	message="The user $username is part of the $userID gang, lives in $dirPath and rides $sh. $userID's place is protected by the passcode $pass, more info about the user here: $idInfo"
	echo "$message"
done < "$file"
