#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for i in *
do
	if [[ ! "$i" =~ ^\..* ]]
	then
		filename=$(echo "$i" | cut -d '-' -f 2-)
		echo "$filename"
	fi
done
