#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine
# it’s executed on
# Use ifconfig to get network interface information and filter for IPv4 addresses
ifconfig | grep -oP '(?<=inet )(\S+)' | cut -d ' ' -f 2
